### PR TITLE
[sailfish-browser] Merge OverlayAnimator's noOverlay state to fullscreenWebPage

### PR DESCRIPTION
**Pull request by rojkov**

### CODE REVIEW

**Comment by rainemak** [comment]
When closing last tab on tab view, I see following warning printed:

```
[W] unknown:-1 - <Unknown File>: QML StateGroup: Can't apply a state change as part of a state definition
```

Secondly when closing active from the tab view and returning back to browser or activating another tab the overlay is showing toolbar immediately => doesn't animate in.

**Comment by rojkov** [comment]
I can't reproduce "QML StateGroup: Can't apply a state change as part of a state definition".
Will check toolbar animation

**Comment by rainemak** [comment]
I'd assume that warning comes due the fact that state is changed twice and first state change triggers second change.

When all tabs are closed or the last tab is closed we prepare overlay open immediately without animation (Overlay.qml line 453 and Overlay.qml line 459). My guess is that somebody somewhere is causing a state change.

In current code (not in this PR), there is another problem that is related.
BrowserPage.qml onStatusChanged handler is executed before the web page is resurrected:

```
         if (status == PageStatus.Inactive && overlay.visible) {
             overlay.animator.hide()
-        } else if (status == PageStatus.Active && webView.contentItem && !overlay.enteringNewTabUrl && !webView.contentItem.fullscreen) {
-            overlay.animator.showChrome()
         }
```

Browser.qml approximately line 237 should be like:

```
         onEnteringNewTabUrlChanged: window.opaqueBackground = overlay.enteringNewTabUrl
+
+        onActiveChanged: {
+            if (active && webView.contentItem && !overlay.enteringNewTabUrl && !webView.contentItem.fullscreen) {
+                overlay.animator.showChrome()
+            }
+        }
```

Overlay.qml handles page stack popping at line 90 and resurrects a tab if it zombie => always causing the webView.contentItem to update.

For example create two tabs, restart browser, let's one tab to load, go to tab view, close the active tab, and pop that tab view.

**Comment by rojkov** [comment]
Well, the state maintenance has become so tangled that I can't wrap my head around it. For example the issue with toolbar not appearing upon exiting fullscreen mode can be solved with

```
diff --git a/src/pages/components/OverlayAnimator.qml b/src/pages/components/OverlayAnimator.qml
index f4672e0..c498e21 100644
--- a/src/pages/components/OverlayAnimator.qml
+++ b/src/pages/components/OverlayAnimator.qml
@@ -195,7 +201,8 @@ Item {
                             atTop = true
                         }

-                        if (webView.contentItem) {
+                        if (webView.contentItem && !webView.contentItem.fullscreen) {
                             webView.contentItem.chrome = animator.state !== "fullscreenWebPage"
                         }
```

Because otherwise there is a conflict in WebView's binding

```
    fullscreenMode: (contentItem && contentItem.chromeGestureEnabled && !contentItem.chrome) ||
                    (contentItem && contentItem.fullscreen)
```

The reason why toolbar lacks animation after switching tabs is because updateState() is called immediately after DeclarativeWebPage::forceChrome() upon tab activation when the Tabs views is still visible. And then it's called once again inside animator's showChrome().

I'm looking at how this can be refactored to something more comprehensible.

**Comment by rainemak** [comment]
Could you check toolbar animation with the above changes? Those changes are needed regardless.

**Comment by rojkov** [comment]
Yes, works nice. No improvements in toolbar animations though

**Comment by rojkov** [comment]
This fixes animation

```
diff --git a/src/pages/components/OverlayAnimator.qml b/src/pages/components/OverlayAnimator.qml
index f4672e0..59a3767 100644
--- a/src/pages/components/OverlayAnimator.qml
+++ b/src/pages/components/OverlayAnimator.qml
@@ -98,13 +101,16 @@ Item {
         ignoreUnknownSignals: true

         onFullscreenModeChanged: {
-            if (!active) {
+            if (!browserPage.active) {
                 return
             }
```

**Comment by rainemak** [comment]
LGTM

**Pull request merged**
