### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by rainemak**
This makes tests to pass. ~~There are occasional failures, will debug that more tomorrow.~~

If/when failure happens

```
rm -rf /home/nemo/.local/share/tst_webview/
```

Failures are easy to reproduce by looping a bit

```
for i in {1..10}; do LOW_MEMORY_DISABLED=1 ./tst_webview; sleep 5 ;done 2>&1 | grep "Totals:"
```

Fyi: @rojkov @tworaz @mikkoharju 

Contains also a small commit that cleanup dead code.

### CODE REVIEW

**Comment by tworaz** [comment]
LGTM

**Comment by rojkov** [comment]
LGTM

**Comment by rainemak** [comment]
Rebased and updated. Added needed preferences so that tst_webview uses the same code path as the real browser.

Tested looping 10x webview tests times on phone and tablet. Also tested full test set with testrunner and all tests were passing.

**Comment by rojkov** [comment]
LGTM

**Pull request merged**
